### ISSUE TITLE
Can't run script

### ISSUE THREAD

**Issue by nmarquest** [coin98/saros-sdk#2]
Hi, 

When running `node myscript.js`

Containing my script:

`import sarosSdk, {
  getSwapAmountSaros,
  ...
} from '@saros-finance/sdk';`

I get the following error: 
`(node:14200) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use  node --trace-warnings ... to show where the warning was created)
C:\Users\...\node_modules\@saros-finance\sdk\src\index.js:1
import * as sarosSdk from './swap';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) `

I have tried adding `"type":"module"` to the package.json file. This seems to work but then breaks node from running all my other TS scripts. 

Can you help?

I'm using: 
NodeJS v14.16.0
NPM v.6.14.11

Thanks.

**Comment by Laikaiyong** [comment]
hi
